version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: weekly
    time: "09:00"
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: kreait/firebase-php
    versions:
    - 5.15.0
    - 5.16.0
    - 5.17.0
    - 5.18.0
  - dependency-name: phpunit/phpunit
    versions:
    - 9.5.1
    - 9.5.2
    - 9.5.3
    - 9.5.4
