language: php
dist: trusty
php: 7.4
service:
  - mysql
stages:
  - test
  - name: deploy-dev
    if: branch = development
  - name: deploy-prod
    if: branch = main
cache:
  directories:
    - $HOME/.m2

jobs:
  include:
    - stage: test
      name: "Run test"
      before_install:
        - openssl aes-256-cbc -K $encrypted_b9929ad0dae9_key -iv $encrypted_b9929ad0dae9_iv -in encrypt.tar.gz.enc -out encrypt.tar.gz -d
        - tar -xzvf encrypt.tar.gz
      install:
        - composer selfupdate
        - composer install --no-interaction
      before_script:
        - mysql -u root -e 'CREATE DATABASE testdb;'
        - mysql -u root testdb < test/test.sql
      script:
        - phpunit --bootstrap vendor/autoload.php --testsuite unit
      after_success:
        - bash <(curl -s https://codecov.io/bash)
    - stage: deploy-dev
      name: "Deploy to heroku-dev"
      before_install:
        - openssl aes-256-cbc -K $encrypted_b9929ad0dae9_key -iv $encrypted_b9929ad0dae9_iv -in encrypt.tar.gz.enc -out encrypt.tar.gz -d
        - tar -xzvf encrypt.tar.gz
      install:
        - composer selfupdate
        - composer install --no-interaction
      before_script:
        - mysql -u root -e 'CREATE DATABASE testdb;'
        - mysql -u root testdb < test/test.sql
      script:
        - phpunit --bootstrap vendor/autoload.php --testsuite unit
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: PV3wPQuswT1wIO45wGCVakszBh8D+CaU9MxbOkjpDGBmg42eFdtuMEHVKcS1wjYUinQr21FsZG7/gurRBBezlum6LZAKfY5vIOufVHMA785N7/yfIgDhda6LfhgRDUrZywVxuQQIj+nREPxjQtzz5M5Ed0GkQbWCJBYIxfsvzo3N0cWiZ0KOkTvcN0FeRZY/O4wpr+sfZ7aGtRsVv3UJX503mJIBITbudRatbxu0jXqpKRqWSZ2H2zAriggnRgA8aRHR6r/J8fj2DBw3wWl9F2t9k/whr+G3NJ/V3tpc/UtTD49h2/JKXJ64OhQSqGMonBmNC7Nbo8OcI0Q/L3356LR63o8/0wg2CH7RgZqxvOSIFZFWMg3hv1EqszQs1nY8/6HlV4/aFMz4lLYmk8nNbTXbOKnUujgKMNV0txVHVho/mQOWDhFHmadq8ju0aXb8exQ145+4ptvR4wH1cMQ491kFMUaadzYKq51mFs2y4bvPmIk1YlqrwUfCZOvLMs6PnN88GjIkp7cr76mzmeibABb/F1qVfWkZO4LsQpHjVC2UD1l7F3ImvDIOah/TBRT2JCjwlc/jK53fcwdcgz6dbe++BvJPgUALtIx+rlr47xw8kISJLEyTEDJiFEW6TWHe5WFSfR+p5KhukrAOUpntzoQeUfK5tdM7LvU6SlFdmd4=
        app: lastquakechile-server-dev
        on:
          branch: development

    - stage: deploy-prod
      name: "Deploy to heroku-prod"
      before_install:
        - openssl aes-256-cbc -K $encrypted_b9929ad0dae9_key -iv $encrypted_b9929ad0dae9_iv -in encrypt.tar.gz.enc -out encrypt.tar.gz -d
        - tar -xzvf encrypt.tar.gz
      install:
        - composer selfupdate
        - composer install --no-interaction
      before_script:
        - mysql -u root -e 'CREATE DATABASE testdb;'
        - mysql -u root testdb < test/test.sql
      script:
        - phpunit --bootstrap vendor/autoload.php --testsuite unit
      deploy:
        provider: heroku
        skip_cleanup: true
        api_key:
          secure: PV3wPQuswT1wIO45wGCVakszBh8D+CaU9MxbOkjpDGBmg42eFdtuMEHVKcS1wjYUinQr21FsZG7/gurRBBezlum6LZAKfY5vIOufVHMA785N7/yfIgDhda6LfhgRDUrZywVxuQQIj+nREPxjQtzz5M5Ed0GkQbWCJBYIxfsvzo3N0cWiZ0KOkTvcN0FeRZY/O4wpr+sfZ7aGtRsVv3UJX503mJIBITbudRatbxu0jXqpKRqWSZ2H2zAriggnRgA8aRHR6r/J8fj2DBw3wWl9F2t9k/whr+G3NJ/V3tpc/UtTD49h2/JKXJ64OhQSqGMonBmNC7Nbo8OcI0Q/L3356LR63o8/0wg2CH7RgZqxvOSIFZFWMg3hv1EqszQs1nY8/6HlV4/aFMz4lLYmk8nNbTXbOKnUujgKMNV0txVHVho/mQOWDhFHmadq8ju0aXb8exQ145+4ptvR4wH1cMQ491kFMUaadzYKq51mFs2y4bvPmIk1YlqrwUfCZOvLMs6PnN88GjIkp7cr76mzmeibABb/F1qVfWkZO4LsQpHjVC2UD1l7F3ImvDIOah/TBRT2JCjwlc/jK53fcwdcgz6dbe++BvJPgUALtIx+rlr47xw8kISJLEyTEDJiFEW6TWHe5WFSfR+p5KhukrAOUpntzoQeUfK5tdM7LvU6SlFdmd4=
        app: lastquakechile-server-prod
        on:
          branch: main
branches:
  only:
    - main
    - development
